server:
  log:
    level: debug
    access_log: false
    format: '%(asctime)-15s %(levelname)s %(message)s'
    file: 
      path: logs/web.log
      maxBytes: 2000
      keep: 10
  host: 127.0.0.1
  port: 5000